name: Arduino Compile Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
          # These 3 libraries are almost always required for these sensors
          libraries: |
            - name: "DHT sensor library"
            - name: "Adafruit BME280 Library"
            - name: "Adafruit Unified Sensor"          	
          # Since your code is in a folder called 'firmware', we specify it here
          sketch-paths: |
            - ./firmware/bme280_sensor/bme280_stress_test.ino
            - ./firmware/dht_sensor/DHT_sensor.ino
          
          # Set to true to see detailed compiler output
          verbose: false